name: keyvault testing

stages:
  - stage: terraform
    jobs:
      - job: terraformbuildjob
        pool:
          vmImage: ubuntu-latest
        variables:
          - group: keyvaultterra
        steps:
          - script: |
              echo "Install Terraform v1.8.2 manually."
              sudo apt-get update && sudo apt-get install -y wget unzip
              wget https://releases.hashicorp.com/terraform/1.8.2/terraform_1.8.2_linux_amd64.zip
              unzip terraform_1.8.2_linux_amd64.zip
              sudo mv terraform /usr/local/bin/
              terraform -version
            displayName: "Install Terraform"

          - script: |
              echo "terraform commands init"
              terraform init
            displayName: "Terraform init"
            # env:
            #   TF_VAR_subscription_id: $(subscription-id)
            #   TF_VAR_client_id: $(client-id)
            #   TF_VAR_client_secret: $(client-secret)
            #   TF_VAR_tenant_id: $(tenant-id)

          - script: |
              echo "sub = $TF_VAR_subscription_id"
            displayName: "Debug Secrets"

          - script: |
              echo "Running terraform plan & apply..."
              terraform plan -out=tfplan
              terraform apply -auto-approve tfplan
            displayName: "Terraform Plan & Apply"
            env:
              # TF_VAR_subscription_id: $(subscription-id)
              # TF_VAR_client_id: $(client-id)
              # TF_VAR_client_secret: $(client-secret)
              # TF_VAR_tenant_id: $(tenant-id)

          - script: |
              echo "⚠️ WARNING: Terraform destroy will run in 60 seconds..."
              sleep 0
              echo "Starting Terraform Destroy..."
              terraform destroy -auto-approve
            displayName: "terraform destroy"
            env:
              # TF_VAR_subscription_id: $(subscription-id)
              # TF_VAR_client_id: $(client-id)
              # TF_VAR_client_secret: $(client-secret)
              # TF_VAR_tenant_id: $(tenant-id)
