trigger:
  - main
variables:
  - group: vargroupterraform
stages:
  - stage: terraform
    jobs:
      - job: terraformbuildjob
        pool:
          vmImage: ubuntu-latest
        variables:
          solution: "**/*.sln"
          buildPlatform: "Any CPU"
          buildConfiguration: "Release"

        steps:
          - script: |
              echo "Install Terraform v1.8.2 manually."
              # Install Terraform v1.8.2 manually
              sudo apt-get update && sudo apt-get install -y wget unzip
              wget https://releases.hashicorp.com/terraform/1.8.2/terraform_1.8.2_linux_amd64.zip
              unzip terraform_1.8.2_linux_amd64.zip
              sudo mv terraform /usr/local/bin/
              terraform -version
            displayName: "Command Line Script"
          - script: |
              export ARM_ACCESS_KEY=$(ARM_ACCESS_KEY)

              echo "terraform commands init"
              terraform init

            displayName: "Command Line Script"

          - script: |
              echo "I am going now terraform commands"

              terraform plan -out=tfplan
              terraform apply -auto-approve tfplan

            displayName: "Command Line Script"
          - script: |
              echo "⚠️ WARNING: Terraform destroy will run in 60 seconds..."
              sleep 60

              echo "Starting Terraform Destroy..."
              terraform destroy -auto-approve
            displayName: "Command Line Script"
          - task: CopyFiles@2
            displayName: "Copy Files to: $(build.artifactstagingdirectory)"
            inputs:
              SourceFolder: "$(agent.builddirectory)"
              TargetFolder: "$(build.artifactstagingdirectory)"

          - task: PublishBuildArtifacts@1
            displayName: "Publish Artifact: drop"
